services:
  qdrant:
    image: qdrant/qdrant:v1.17
    container_name: spring-ai-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - spring-ai
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    networks:
      - spring-ai
  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317" #grpc
      - "4318:4318" #http
    environment:
      COLLLECTOR_OTLP_ENABLED: true
    networks:
      - spring-ai

networks:
  spring-ai:
    driver: bridge

volumes:
  grafana-storage: