server:
  servlet:
    context-path: /api
spring:
  application:
    name: mcpclient
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG