server:
  servlet:
    context-path: /api
spring:
  application:
    name: spring-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:test-key}
      chat:
        model: gpt-5.4-mini
    ollama:
      base-url: http://fedora:11434
      chat:
        model: llama3.1:8b
    chat:
      client:
        enabled: false
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG